LedEffects.h
SETFULLCOLOR
define for the setfullcolor effect, used for main switch
Referenced by main.
FILLUP
define for the the fillup effect, used for main switch
Referenced by main.
BLINK
define for the blink effect, used for main switch
Referenced by main.
RUNLED
define for the runled effect, used for main switch, refers to the runled init
Referenced by main.
ALTERNATE
define for the alternating effect, used for main switch, refers to the alternate init
Referenced by main.
RECOLOR
define for the recolor effect, used for main switch
Referenced by main.
FADE
define for the fade effect, used for main switch
Referenced by main.
INITRAINBOW
define for the initrainbow function, used for main switch
Referenced by main.
ROTATE_R
define for the the rotate function right, used for main switch
Referenced by main.
ROTATE_L
define for the the rotate function left, used for main switch
Referenced by main.
CUSTOM
define for the custom effect, used for main switch, every LED is filled in a userdefined color (up to MAXNUMCOLORS, then reloop the colors)
Referenced by main.
EASTEREGG
define for the easteregg effect, used for main switch
Referenced by main.
uint8_t map(uint8_t x, uint8_t in_min, uint8_t in_max, uint8_t out_min, uint8_t out_max)
Arduino map function; used for color conversion.
uint8_t x: value to map uint8_t in_min : minimum value input reference uint8_t in_max : maximum value input reference uint8_t out_min : minimum value output reference uint8_t out_max : maximum value output reference uint8_t : mapped value referring to the input This function is used for color conversion from 8 Bit to 24 Bit colors; How it works: in_min < x < in_max convert to out_min < returnvalue < out_max by positioning the x proportionally in the new number range
Referenced by colorconv8to24.
struct color24bit colorconv8to24(uint8_t startcolor)
color conversion function; converts a 8 Bit color (RGB 3-3-2) to a 24 Bit color (RGB 8-8-8)
uint8_t startcolor: 8 Bit color to convert struct color24bit : 24 Bit color result This function converts the 8 Bit color to a 24 Bit color depending on the ledtype. This is neccessary because of differnt color formats (WS2811->RGB ; WS2812->GRB). Original the whole environment was for WS2812 LEDs!
References color24bit::blue, color24bit::green, ledtype, map, color24bit::red.
Referenced by easteregg, main.
void effectdelay(uint16_t delay)
simple delay function; no concrete delay time
uint16_t delay : delay value void This function is just a variable delay, there is no coherence with a concrete time (i.e. s, ms)
References PacketComplete.
Referenced by blinkled, eastereggbase, faden, fillup, main, recolor, run_alternating, runrunled.
void setfullcolor(struct color24bit color, uint8_t *lightdata)
Set all LEDs to the chosen color; run transmit2leds afterwards to update the LEDs.
struct color24bit color : color to set uint8_t *lightdata : lightdata array that holds the color values for the stribe void This function sets the lightdata array. To update the stribe run transmit2leds afterwards!
References color24bit::blue, color24bit::green, NumOfLeds, color24bit::red.
Referenced by blinkled, faden, init_alternating, initrunled, main, resetstribe.
void resetstribe(uint8_t *lightdata)
Set all LEDs off; run transmit2leds afterwards to update the LEDs.
uint8_t *lightdata : lightdata array that holds the color values for the stribe void This function sets the lightdata array to 0x00. To update the stribe run transmit2leds afterwards!
References color24bit::blue, color24bit::green, color24bit::red, setfullcolor.
Referenced by blinkled.
void rotate(uint8_t *lightdata, uint8_t direction)
Rotate the lightdata for 1 LED Position; run transmit2leds afterwards to update the LEDs.
uint8_t *lightdata : lightdata array that holds the color values for the stribe uint8_t direction : direction to rotate void This function rotates lightdata array. To update the stribe run transmit2leds afterwards! The rotation "moves every LED" by one step, the overflowing LED is appended at the other ending. Example: RED BLUE YELLOW GREEN ... rotate... BLUE YELLOW GREEN RED other direction: RED BLUE YELLOW GREEN ... rotate... GREEN RED BLUE YELLOW
References NumOfLeds.
Referenced by eastereggbase, main, rotateN, run_alternating, runrunled.
void rotateN(uint8_t *lightdata, uint8_t direction, uint8_t width)
Rotate the lightdata for n LED Positions; run transmit2leds afterwards to update the LEDs.
uint8_t *lightdata : lightdata array that holds the color values for the stribe uint8_t direction : direction to rotate uint8_t width : width to rotate void This function rotates lightdata array. To update the stribe run transmit2leds afterwards! The rotation "moves every LED" by n steps, the overflowing LEDs are appended at the other ending. Example: RED BLUE YELLOW GREEN PINK ... rotate 2 ... YELLOW GREEN PINK RED BLUE other direction: RED BLUE YELLOW GREEN PINK ... rotate 2 ... GREEN PINK RED BLUE YELLOW
References rotate.
void initrunled(struct color24bit color, uint8_t *lightdata, struct color24bit background)
init the runled effect; run runrunled afterwards to start the effect
This function initializes the running LED effect. The running LED effect has a background color that is used for all LEDs except one. One LED is in the foreground color an moves stepwise along the stribe. The initialization prepares the lightdata array by setting one LED at the start position and filling the others with the background color. struct color24bit color : 24 Bit color for the effect uint8_t *lightdata : lightdata array that holds the color values for the stribe struct color24bit background : 24 Bit color for the effect background void Run runrunled afterwards to start the effect!
References changeled, setfullcolor.
Referenced by main.
void runrunled(uint8_t *lightdata, uint8_t direction)
Do the runled effect; before this function is called the lightdata needs to be initiliazed using initrunled!
This function runs the running LED effect. The running LED effect has a background color that is used for all LEDs except one. The one LED moves stepwise to the next position depending on the chosen direction. Direction 0/1 are right/left, direction 2 runs from left to right an back again. For direction 0/1 the running LED overflows and begins on the other ending. uint8_t *lightdata : lightdata array that holds the color values for the stribe uint8_t direction : movement direction, 0/1 = right/left, 2 = left->right and back void No need to run transmit2leds afterwards! This is already done in the function. The function is interrupted if a new UART package is completely received so a new effect gets active.
References effectdelay, effectime, NumOfLeds, PacketComplete, rotate, transmit2leds.
Referenced by main.
void blinkled(struct color24bit color, uint8_t *lightdata)
blink the whole stribe; this function does not need another function call
This function creates a blinking effect. First all LEDs are set to the chosen color, after the defined delay the LEDs are turned off. This is repeated in the main while loop. struct color24bit color : color for the blink effect uint8_t *lightdata : lightdata array that holds the color values for the stribe void No need to run transmit2leds afterwards! This is already done in the function.
References effectdelay, effectime, resetstribe, setfullcolor, transmit2leds.
Referenced by main.
void init_alternating(struct color24bit color, struct color24bit backcolor, uint8_t *lightdata)
initialize the alternating function; call run_alternating afterwards
This function initializes the alternating effect. The effect assigns every even LED number in one color and the odd numbers in the background color. If the effect is running, the odd and even LED switch positions. struct color24bit color : color for the alternate effect (Init even LEDs) struct color24bit backcolor : color for the alternate effect bakckground (Init odd LEDs) uint8_t *lightdata : lightdata array that holds the color values for the stribe void Run run_alternating afterwards to start the effect!
References changeled, NumOfLeds, setfullcolor.
Referenced by main.
void run_alternating(uint8_t *lightdata)
Run the alternating effect; call init_alternating before.
This function runs the alternating effect. The effect assigns every even LED number in one color and the odd numbers in the background color. If the effect is running, the odd and even LED switch positions. This function rotates the LEDs by one position to achieve the effect. The rotation direction is not of importance. uint8_t *lightdata : lightdata array that holds the color values for the stribe void No need to run transmit2leds afterwards! The effect is generated by the main while loop.
References effectdelay, effectime, rotate, transmit2leds.
Referenced by main.
void recolor(struct color24bit color, uint8_t *lightdata)
Recolor the LED stribe; no other function call is necessary.
This function generates a recolor effect. The old configuration of the LEDs is overwritten with the new color step by step. When the whole stribe is filled with the new color the effect ends. struct color24bit color : color that is used for recoloring uint8_t *lightdata : lightdata array that holds the color values for the stribe void No need to run transmit2leds afterwards! The effect is standalone and ends if the stribe is recolored.
References changeled, effectdelay, effectime, NumOfLeds, PacketComplete, transmit2leds.
Referenced by main.
void faden(struct color24bit color, uint8_t *lightdata)
Generate a fading color effect. No other function call is necessary.
This function generates a fading color effect. At the beginning the whole stribe is filled with the chosen color. The color intensity of each color channel (blue, red, green) is decreased until the stribe is off. After that the color values are increased until the chosen color values are reached. The effect looks different depending on the chosen color because the color value proportion is not kept over the whole effect. struct color24bit color : color that is used for the fading effect uint8_t *lightdata : lightdata array that holds the color values for the stribe void No need to run transmit2leds afterwards! The effect is standalone and ends is looped in the main while loop. The color value proportion is not kept over the whole effect.
References color24bit::blue, effectdelay, effectime, color24bit::green, PacketComplete, color24bit::red, setfullcolor, transmit2leds.
Referenced by main.
void initrainbow(uint8_t *lightdata)
Initialize a rainbow on the color array; to show the rainbow run transmit2leds afterwards.
This function fills the color array with rainbow colors. For this effect the color array is filled with different colors that are calculated by increasing and decreasing the color channels to loop over a RGB palette. uint8_t *lightdata : lightdata array that holds the color values for the stribe void Run transmit2leds afterwards! A nice effect is to rotate the array stepwise after the rainbow initialization (run transmit2leds after every rotation). The effect directly sets color values, so there may be a problem with the color profiles (RGB vs. GRB). The function was primary written for WS2812 LEDs (GRB)! The effect needs a minimum number of 20 LEDs to look nice!
References color24bit::blue, changeled, color24bit::green, NumOfLeds, color24bit::red.
Referenced by main.
void eastereggbase(struct color24bit color, uint8_t *lightdata)
Initialize the easteregg; do not use directly; this function is used by the easteregg function.
struct color24bit color : color for the easteregg uint8_t *lightdata : lightdata array that holds the color values for the stribe void Do not use this function directly; this function is used by the easteregg function
References changeled, effectdelay, effectime, NumOfLeds, PacketComplete, rotate, transmit2leds.
Referenced by easteregg.
void easteregg(uint8_t *lightdata)
Run the easteregg; No other function call is necessary.
uint8_t *lightdata : lightdata array that holds the color values for the stribe void Just try it :-) funny looking effect
References colorconv8to24, eastereggbase, PacketComplete.
Referenced by main.
void fillup(struct color24bit color, struct color24bit backcolor, uint8_t *lightdata)
This function fills up the stribe; No other function call is necessary.
This function fills up the whole stribe and beginns again if it is finished. First one LED moves in the chosen color stepwise through the whole stribe and recolors all LEDs in the background color which have already been passed. At the end of the stribe the LED stays an the next single LED is going to move to the last-1 position. The next LED to the last-2 position. This is going on until the whole stribe is colored. Then the effect restarts (main while loop). struct color24bit color : foreground color for the moving LED struct color24bit backcolor : background color uint8_t *lightdata : lightdata array that holds the color values for the stribe void This is a standalone effect.
References changeled, effectdelay, effectime, NumOfLeds, PacketComplete, transmit2leds.
Referenced by main.