Lightstribe.h
void changeled(struct color24bit color, uint8_t *lightdata, uint8_t lednr)
change the color of one LED at a specific position; run transmit2leds afterwards to update the LEDs
struct color24bit color : 24 bit color in GRB format uint8_t *lightdata : pointer to the complete lightdata that contains all color values uint8_t lednr : position of the LED that should be changed void the right color format is created using the colorconv8to24-function with the ledtype predefined
References color24bit::blue, color24bit::green, NumOfLeds, color24bit::red.
Referenced by eastereggbase, fillup, init_alternating, initrainbow, initrunled, main, recolor.
void setled(struct color24bit color, uint8_t *lightdata, uint8_t lednr)
set the color of one LED at a specific position, all others are off; run transmit2leds afterwards to update the LEDs
struct color24bit color : 24 bit color in GRB format uint8_t *lightdata : pointer to the complete lightdata that contains all color values uint8_t lednr : position of the LED that should be set void the right color format is created using the colorconv8to24-function with the ledtype predefined; all other LEDs are cleared so they are off
References color24bit::blue, color24bit::green, NumOfLeds, color24bit::red.
void transmit2leds(uint8_t lightdata[])
transmit the color array to the stribe
To control the LEDs of type WS2811/WS2812 a critical timing is necessary. To achieve the correct timing and to create effects the lightdata is stored in an array first. All operations effect the color array. If the color array is prepared it is transmitted to the stribes via a one-wire protocol using this function. This function generates the high and low times using assembler NOPs to achieve the timing. The number of NOPs are stored in macros for transmitting a Low Bit (SETLOW) or a High Bit (SETHIGH). This function should not be changed or optimized because of the timing! uint8_t lightdata[] : data with the colors for each LED to control void This function should not be changed or optimized because of the timing! Do not use higher optimization than O1!!! Do not remove the {} brackets because SETLOW/SETHIGH are definitions with several commands!
References NumOfLeds.
Referenced by blinkled, eastereggbase, faden, fillup, main, recolor, run_alternating, runrunled.